### ISSUE TITLE
Transaction id может оказаться дубликатом

### ISSUE THREAD

**Issue by feed4rz** [bifot/node-qiwi#1]
Несмотря на рекомендации QIWI, очень высока вероятность того, что бот отправит 2 транзакции одновременно и одна не пройдет из-за дубликата id.

Нужно это
```JAVASCRIPT
String(new Date().getTime() * 1000)
```
Заменить на вот это
```JAVASCRIPT
String(Date.now())
```

**Comment by bifot** [comment]
Отправь пулл реквест.
