### ISSUE TITLE
Актуальность/использование

### ISSUE THREAD

**Issue by Nekspsy** [bifot/node-qiwi#3]
Здравствуйте, ваш скрипт актуален?
Могу ли я его использовать со своими номером телефоном и апи ключем?

**Comment by bifot** [comment]
Привет, да.

**Comment by Nekspsy** [comment]
Подскажи, если не сложно, как использовать в таком случае? не могу понять куда ввести номер телефона и апи ключ, переменных по них же вроде нет. Сори, я новичок
Вообще задача стоит: авторизоваться, получить последние платежи и проверить платеж по комменту

**Comment by Nekspsy** [comment]
Буду очень благодарен, если кто-нибудь подскажет хотя бы как пройти авторизацию по телу:апи ключу на ноде
